default:
  image: python:3.8-slim

stages:
  - lint
  - test
  - document
  - install
  - test installed scripts
  - api

variables:
  the_proxy: "http://host.docker.internal:3128"

.before_script_template:
  before_script:
    - pip3 install pipenv

lint:
  extends: .before_script_template
  stage: lint
  script:
  - pipenv run pip install flake8
  # stop the build if there are Python syntax errors or undefined names
  - pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
  - pipenv run flake8 --ignore=W504 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

test:
  extends: .before_script_template
  stage: test
  variables:
    DATA: "/the_data/data/"
    MODEL: "/the_data/model/"
    PYTHONPATH: '.'
  script:
  - pipenv install -d --skip-lock
  - pipenv run coverage run --source renard_joint,scripts -m pytest
  - pipenv run coverage report
  - pipenv run python scripts/pipeline.py conll04 evaluate
  - pipenv run python scripts/pipeline.py internal evaluate
  - pipenv run python scripts/pipeline.py conll04 predict "Adrien tries data harvesting" "It's probably working"
  - pipenv run python scripts/pipeline.py internal predict "Dirty company does bad coal activity" "Nice company treats people equally"
  - pipenv run python scripts/spert.py conll04 evaluate 19
  - pipenv run python scripts/spert.py scierc evaluate 19
  - pipenv run python scripts/spert.py internal evaluate 26
  - pipenv run python scripts/spert.py conll04 predict 19 "Dirty company does bad coal activity" "Nice company treats people equally"
  - pipenv run python scripts/spert.py scierc predict 19 "Dirty company does bad coal activity" "Nice company treats people equally"
  - pipenv run python scripts/spert.py internal predict 26 "Dirty company does bad coal activity" "Nice company treats people equally"
#  - pipenv run python scripts/spert.py conll04 train
#  - pipenv run python scripts/spert.py scierc train
#  - pipenv run python scripts/spert.py internal train

document:
  image: docker:20.10.5-dind
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  stage: document
  script:
  - apk update
  - apk add py3-pip gcc build-base freetype-dev libpng-dev openblas-dev
  - pip3 install pipenv
  - pipenv install -d --skip-lock
  - cd docs
  - pipenv run make html
  - docker run -v "build/html":/web -p 8000:8000 --name sphinx-server dldl/sphinx-server
  - docker save sphinx-server > data_harvesting_docs.tar
  artifacts:
    paths:
      - docs/build/html
    expire_in: 1 week

install:
  extends: .before_script_template
  stage: install
  script:
  - pipenv install --skip-lock
  - pipenv lock -r > requirements.txt
  - pipenv run python3 setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist
    expire_in: 1 week

test_install:
  extends: .before_script_template
  stage: test installed scripts
  script:
  - pipenv install --skip-lock
  - pipenv lock -r > requirements.txt
  - pipenv install .
  - pipenv run python pipeline.py conll04 evaluate
  - pipenv run python pipeline.py internal evaluate
  - pipenv run python pipeline.py conll04 predict "Adrien tries data harvesting" "It's probably working"
  - pipenv run python pipeline.py internal predict "Dirty company does bad coal activity" "Nice company treats people equally"
  - pipenv run python spert.py conll04 evaluate 19
  - pipenv run python spert.py scierc evaluate 19
  - pipenv run python spert.py internal evaluate 26
  - pipenv run python spert.py conll04 predict 19 "Dirty company does bad coal activity" "Nice company treats people equally"
  - pipenv run python spert.py scierc predict 19 "Dirty company does bad coal activity" "Nice company treats people equally"
  - pipenv run python spert.py internal predict 26 "Dirty company does bad coal activity" "Nice company treats people equally"
#  - pipenv run python spert.py conll04 train
#  - pipenv run python spert.py scierc train
#  - pipenv run python spert.py internal train

api:
  stage: api
  image: docker:20.10.5-dind
  services:
    - name: docker:dind
      alias: docker
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  script:
  - pipenv install -d --skip-lock
  - cd API
  - docker build --build-arg the_proxy=$the_proxy -t data_harvesting_api:latest .
  - docker save data_harvesting_api:latest > data_harvesting_api.tar
  artifacts:
    paths:
      - API/data_harvesting_api.tar
    expire_in: 1 week
