language: python
python:
  - "3.7"
  - "3.8"
git:
  depth: 3
  lfs_skip_smudge: true
install:
  - python -m pip install --upgrade pip
  - pip install pipenv
  - pipenv install --dev
dependencies:
  - mkdir model && cd model
  - mkdir spert && mkdir ner && mkdir re && cd spert
  - wget -O internal_epoch_26.model https://cdn-130.anonfiles.com/v9j1F5Aau8/7607feed-1628247205/internal_epoch_26.model # ClimLL
  - wget -O conll04_epoch_19.model https://cdn-107.anonfiles.com/zdi3FbA5u3/f8b9d9fa-1628247235/conll04_epoch_19.model # CoNLL04
  - wget -O scierc_epoch_19.model https://cdn-128.anonfiles.com/tcj0F5Aau5/0f85429a-1628247125/scierc_epoch_19.model && cd ../ner # SciERC
  - wget -O internal_nn_1024.model https://cdn-129.anonfiles.com/Dbo5FaA9u6/165f5ae3-1628247316/internal_nn_1024.model # ClimLL
  - wget -O conll04_nn_1024.model https://cdn-133.anonfiles.com/70ofFcA2uf/fcde85d4-1628247288/conll04_nn_1024.model && cd ../re # CoNLL04
  - wget -O internal_100.model https://cdn-106.anonfiles.com/l8s6F9A9u8/37a2698c-1628259684/internal_100.model # ClimLL
  - wget -O conll04_100.model https://cdn-131.anonfiles.com/p9u9F8Acu2/db5e65ac-1628259731/conll04_100.model && cd ../.. # CoNLL04
  - mkdir data && cd data
  - mkdir conll04 && cd conll04 && wget -O CoNLL04.zip https://cdn-105.anonfiles.com/n6e4H9A6u3/92b41668-1628259818/CoNLL04.zip && unzip CoNLL04.zip && cd ..
  - mkdir scierc && cd scierc && wget -O sciERC.zip https://cdn-106.anonfiles.com/p5eeH7A1u1/6b5b8428-1628259777/sciERC.zip && unzip sciERC.zip && cd ../../..
lint:
  - pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  - pipenv run flake8 . --count --exit-zero --extend-ignore=W504 --max-complexity=10 --max-line-length=120 --statistics
test:
  - pipenv run coverage run --source renard_joint -m pytest
  - pipenv run bandit -r renard_joint
  - pipenv run python renard_joint/_scripts/pipeline.py conll04 evaluate
  - pipenv run python renard_joint/_scripts/pipeline.py internal evaluate
  - pipenv run python renard_joint/_scripts/pipeline.py conll04 predict "Adrien tries data harvesting" "It's probably working"
  - pipenv run python renard_joint/_scripts/pipeline.py internal predict "Dirty company does bad coal activity" "Nice company treats people equally"
  - pipenv run python renard_joint/_scripts/spert.py conll04 evaluate 19
  - pipenv run python renard_joint/_scripts/spert.py scierc evaluate 19
  - pipenv run python renard_joint/_scripts/spert.py internal evaluate 26
  - pipenv run python renard_joint/_scripts/spert.py conll04 predict 19 "Dirty company does bad coal activity" "Nice company treats people equally"
  - pipenv run python renard_joint/_scripts/spert.py scierc predict 19 "Dirty company does bad coal activity" "Nice company treats people equally"
  - pipenv run python renard_joint/_scripts/spert.py internal predict 26 "Dirty company does bad coal activity" "Nice company treats people equally"
document:
  - cd docs
  - pipenv run make html
build:
  - pipenv install --skip-lock
  - pipenv run pip freeze > requirements.txt
  - pipenv run python3 setup.py sdist bdist_wheel
  - pipenv run twine check dist/*

after_sucess:
  codecov
