# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        fetch-depth: 0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev --skip-lock
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        pipenv run flake8 --ignore=W504 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
    - name: Download all
      env:
        DRIVE_API_KEY: ${{ secrets.DRIVE_API_KEY }}
      run: |
        echo $DRIVE_API_KEY  # make sure it exists even though it's masked
        mkdir model && cd model
        mkdir spert && mkdir ner && mkdir re && cd spert
        wget -O internal_epoch_26.model https://www.googleapis.com/drive/v3/files/1k6CZ74uJSJgwCCk-fUTouEWy4PK2W0bx?alt=media\&key=$DRIVE_API_KEY  # ClimLL
        wget -O conll04_epoch_19.model https://www.googleapis.com/drive/v3/files/1uf1uD9uxEEu1QxrEMYaZzIjnWZLt_36Q?alt=media\&key=$DRIVE_API_KEY # CoNLL04
        wget -O scierc_epoch_19.model https://www.googleapis.com/drive/v3/files/1go-9ftQS01oAC5FqM6t_I5iQ87nF1hAg?alt=media\&key=$DRIVE_API_KEY && cd ../ner # SciERC
        wget -O internal_nn_1024.model https://www.googleapis.com/drive/v3/files/1UjvSVzxEAPBW7fbfL53Ub1kxOKXNEcf5?alt=media\&key=$DRIVE_API_KEY # ClimLL
        wget -O conll04_nn_1024.model https://www.googleapis.com/drive/v3/files/1C5jQc9DUsC_baVQVnETGM5MHTA_P69Wd?alt=media\&key=$DRIVE_API_KEY && cd ../re # CoNLL04
        wget -O internal_100.model https://www.googleapis.com/drive/v3/files/1CpZC0TWpN7hXwumCFzGRS5YpJpdQRpQ7?alt=media\&key=$DRIVE_API_KEY # ClimLL
        wget -O conll04_100.model https://www.googleapis.com/drive/v3/files/1xpjs92IEYpnaHzeLgqy3UsQ1_zxcJ-oL?alt=media\&key=$DRIVE_API_KEY && cd ../.. # CoNLL04
        mkdir data && cd data
        wget -O CoNLL04.zip https://www.googleapis.com/drive/v3/files/1LKAvkgk8ePvERHwh6YtAWF13XJxdRu3K?alt=media\&key=$DRIVE_API_KEY && jar xvf CoNLL04.zip
        wget -O sciERC.zip https://www.googleapis.com/drive/v3/files/1UXkI_Were9LV8nhUkXPZF1oFi7KzBjch?alt=media\&key=$DRIVE_API_KEY && jar xvf sciERC.zip && cd ..
    - name: Test coverage
      run: |
        pipenv run coverage run --source renard_joint -m pytest -rxXs
        pipenv run bandit -r renard_joint
        export PYTHONPATH=.
        pipenv run python renard_joint/_scripts/pipeline.py conll04 evaluate
        pipenv run python renard_joint/_scripts/pipeline.py conll04 predict "Adrien tries data harvesting" "It's probably working"
        pipenv run python renard_joint/_scripts/pipeline.py internal predict "Dirty company does bad coal activity" "Nice company treats people equally"
        pipenv run python renard_joint/_scripts/spert.py conll04 evaluate 19
        pipenv run python renard_joint/_scripts/spert.py scierc evaluate 19
        pipenv run python renard_joint/_scripts/spert.py conll04 predict 19 "Dirty company does bad coal activity" "Nice company treats people equally"
        pipenv run python renard_joint/_scripts/spert.py scierc predict 19 "Dirty company does bad coal activity" "Nice company treats people equally"
        pipenv run python renard_joint/_scripts/spert.py internal predict 26 "Dirty company does bad coal activity" "Nice company treats people equally"
        export PYTHONPATH=
#       pipenv run python _scripts/spert.py conll04 train
#       pipenv run python _scripts/spert.py scierc train
#       pipenv run python _scripts/spert.py internal train
    - name: Vulnerability
      run: |
        pipenv run bandit -r renard_joint
    - name: Install
      run: |
        pipenv run pip freeze > requirements.txt
        pipenv run pip install .
        pipenv run pipeline conll04 evaluate
        pipenv run pipeline conll04 predict "Adrien tries data harvesting" "It's probably working"
        pipenv run pipeline internal predict "Dirty company does bad coal activity" "Nice company treats people equally"
        pipenv run spert conll04 evaluate 19
        pipenv run spert scierc evaluate 19
        pipenv run spert conll04 predict 19 "Dirty company does bad coal activity" "Nice company treats people equally"
        pipenv run spert scierc predict 19 "Dirty company does bad coal activity" "Nice company treats people equally"
        pipenv run spert internal predict 26 "Dirty company does bad coal activity" "Nice company treats people equally"
    - name: Build and Commit documentation to gh-pages branch
      uses: sphinx-notes/pages@master
      with:
        documentation_path: 'docs/source'
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
    - name: Build and check package
      run: |
        pipenv run pipenv-setup sync --dev
        pipenv run pip install --upgrade keyring keyrings.alt
        python setup.py build sdist bdist_wheel
        pipenv run twine check dist/*
